=== hungpv77/consume-soap/src/main/api/weather-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "Location": {
      "type": "string"
    },
    "Time": {
      "type": "string"
    },
    "Wind": {
      "type": "string"
    },
    "Visibility": {
      "type": "string"
    },
    "SkyConditions": {
      "type": "string"
    },
    "Temperature": {
      "type": "string"
    },
    "DewPoint": {
      "type": "string"
    },
    "RelativeHumidity": {
      "type": "string"
    },
    "Pressure": {
      "type": "string"
    },
    "Status": {
      "type": "string"
    }
  },
  "required": [
    "Location",
    "Time",
    "Wind",
    "Visibility",
    "SkyConditions",
    "Temperature",
    "DewPoint",
    "RelativeHumidity",
    "Pressure",
    "Status"
  ]
}

=== hungpv77/consume-soap/src/main/api/weather-example.json
{
  "Location": "Sepang/KL International Airport, Malaysia (WMKK) 02-44N 101-42E 22M",
  "Time": "Aug 04, 2016 - 04:00 AM EDT / 2016.08.04 0800 UTC",
  "Wind": " from the S (170 degrees) at 6 MPH (5 KT) (direction variable):0",
  "Visibility": " greater than 7 mile(s):0",
  "SkyConditions": " mostly cloudy",
  "Temperature": " 87 F (31 C)",
  "DewPoint": " 71 F (22 C)",
  "RelativeHumidity": " 58%",
  "Pressure": " 29.74 in. Hg (1007 hPa)",
  "Status": "Success"	
}
